### ISSUE TITLE
Provide XSLT to render tool card in HTML

### ISSUE THREAD

**Issue by bug1303** [bio-tools/biotoolsSchema#101]
Given a tool record as biotoolsSchema 3.0.0-compliant XML (or alternatively in json as shown on https://bio.tools/api/signalp), it would be helpful to see how that would be rendered on bio.tools (or an approximation of that).
The extensive description of the schema in the docs and the example files provided are really helpful.
However, when working with a larger number of such tool records, it would be great to have an easy way of transforming these to nicely rendered (or at least better human-readable) HTML, in order to sanity check and improve entries before upload to bio.tools.

**Comment by joncison** [comment]
It wouldn't be a huge work to do this, given a template HTML to map to. Alternatively it could be a nice feature to develop for https://github.com/bio-tools/edamToolAnnotator, a sort of "Preview".
