### ISSUE TITLE
New field to link to Debian Med source & binary packages

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#11]
Template URL for binary packages:
packages.debian.org/binaryPackageName

Template URL to source packages is:
packages.debian.org/source/sourcePackageName

**Comment by matuskalas** [comment]
I think we could hack them into 1.4.x in whichever form.

But in 2.0 they should probably be kinds of generic links, perhaps with a "role" annotated. E.g. "deb source package"(?) similar to e.g. "wikipedia" links. Or should these kinds of roles be configured globally depending on the URI domain etc??

**Comment by joncison** [comment]
done in 2.0-beta02

<download->type> enum includes ""Debian source package" and "Debian binary package"
