### ISSUE TITLE
Inconsistencies between elements

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsSchema#123]
The `<xs:documentation>` of the tool _description_ says that "This can be a few sentences copy-pasted from the software homepage.  Minimum 10 and maximum 500 characters.". The actual `<xs:maxLength>` restriction is 1000 (specified under _textType_, but also explicitly under _description_ itself).

The incorrect max length (500) is also specified in biotoolsDocs: https://biotools.readthedocs.io/en/latest/api_usage_guide_dev.html#description

---

DOIs can be specified in two places: under _publications_ and under _otherID_. Both specify the pattern of the required regex separately, wouldn't it be better to specify the pattern once and reference it in both places to avoid inconsistencies?

Because right now the patterns are different, with the one under _publications_ being `10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+` and the one under _otherId_ being `(doi|DOI):?10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+` with the difference being in the prefix allowed in the second case: `(doi|DOI):?`.

Furthermore, the DOI Handbook says that "doi:" must be lowercase: https://www.doi.org/doi_handbook/2_Numbering.html#2.6.1.

While the lowercase/uppercase issue can be debatable, the current pattern probably contains a mistake in that the ":" character is made optional rather than "doi:" or "DOI:", that is the regex should rather be `(doi:|DOI:)?`.

---

The pattern restricting a version number `[\p{Zs}A-Za-z0-9+\.,\-_:;()]*` appears also in two different places, could it be specified only once (under _versionType_) to avoid potential future inconsistencies (like happened with DOI)?

**Comment by joncison** [comment]
@jaanisoe thanks a million for these detailed points.  All addressed, *except* for the multiple definitions of the DOI regex - there are technical reasons why it's not really possible / convenient to have a single pattern definition (there is now a single pattern definition for version number though!)

The insistence on doi|DOI prefix was just wrong and is gone.
