### ISSUE TITLE
Check compatibility with relevant schemes and standards

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#13]
Including:
- SPDX (The Software Package Data Exchange) specification is a standard format for communicating the components, licenses and copyrights associated with a software package
  http://spdx.org/
- HCLS (Dataset Descriptions: from Semantic Web in Health Care and Life Sciences Interest Group)
  http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/#s4_1
- W3CPROV (provenance information)
  https://www.w3.org/TR/prov-overview/
- OntoSoft
  http://ontosoft.org/ontology/software/
- RFC standard for describing URL templates (URL scheme)
  https://tools.ietf.org/html/rfc6570
  (see also https://support.google.com/webmasters/answer/6080550?hl=en)
- schema.org
  http://www.schema.org/docs/extension.html
- biodbcore
  http://database.oxfordjournals.org/content/2011/baq027.full
- GA4GH tool registry schema
  https://github.com/ga4gh/tool-registry-schemas/
- re3data.org Schema  for the Description of Research Data Repositories
  https://blog.datacite.org/new-re3data-schema-and-search-functionality/

**Comment by joncison** [comment]
NB @matuskalas & @hmenager : this would be required for the publication I think

**Comment by joncison** [comment]
cc @albangaignard  - see above!

Also see the spreadsheet on the mapping work done within BioSchema:
https://docs.google.com/spreadsheets/d/1D0aQl-Ocp8Fi7a-drKV1Faed6tYUgGwzEM8xypa8S2Y/edit#gid=1261485211

**Comment by joncison** [comment]
Chris Morris says ...
"Have you considered making bio.tools compatible with OpenAIRE? It already has more or less the right metadata, but would probably need to present it differently:
   https://guidelines.openaire.eu/en/latest/data/index.html
This would benefit depositors by providing an automated route for software outputs to appear on their project dashboard along with publications - and therefore provide an incentive to deposit a description on bio.tools.

I have suggested to OpenAIRE that they add "web application" as a new category of project output.
"

**Comment by joncison** [comment]
@albangaignard OpenAIRE makes heavy use of Dublin Core so I think is very useful for the analysis of other vocabularies / mapping in biotoolsSchema being done in context of https://github.com/bio-tools/biotoolsRdf.  cc @matuskalas FHI.

**Comment by alessiabardi** [comment]
Hi all, this is Alessia from OpenAIRE. As @joncison requested by email I am adding here the list of fields that will be available in the OpenAIRE guidelines for software:
_Property (optionality) | Datacite metadata field_
where optionality is one of M(andatory), R(ecommended), O(ptional):

1. Identifier (M) | datacite:identifier
2. Author (M) | datacite:creator
3. Contact Person (O) | datacite:contributor
4. Contact Group (O) | datacite:contributor
5. Name (M) | datacite:title
6. Repository (R) | datacite:publisher
7. Software Type (M) | datacite:resourceType
8. Subject (R) | datacite:subject
9. Release date (R) | datacite:date
10. Description language (O) | datacite:language
11. Alternate identifier (O) | datacite:alternateIdentifier
12. Landing page (R) | datacite:alternateIdentifier
13. Distribution location (R) | datacite:alternateIdentifier
14. Documentation (R) | datacite:relatedIdentifier
15. RelatedIdentifier (O) | datacite:relatedIdentifier
16. Programming Language (R) | datacite:format
17. Version Number (R) | datacite:version
18. Access Rights (M) | datacite:rights
19. Licence Condition (R) | datacite:rights
20. Description (R) | datacite:description
21. Tool (R) | datacite:description
22. Funding Reference (R) | datacite:fundingReference
23. Distribution form (O) | datacite:description

**Comment by joncison** [comment]
Thanks Alessia, very helpful!   In the 1st instance we'll look at mapping this to biotoolSchema fields and then formally annotating that mapping in the XSD itself (which is a prelude to other things, that can come later...)

**Comment by joncison** [comment]
Hi @alessiabardi 

Quick question: which of these should I be looking at:
1. https://guidelines.openaire.eu/en/latest/data/application_profile.html
2. https://software-guidelines.readthedocs.io/en/latest/application_profile.html

?

I assume the first is more up-to-date?

Cheers !

**Comment by alessiabardi** [comment]
The first link is for the guideline for Data Archive managers.
The second link is for the guideline for Software Software Repository Managers. 
We also have a third guideline for "other types of research products" (https://guidelines-other-products.readthedocs.io), which is meant for research products that are not scientific publication, software and datasets. Examples are tools, methods, protocols, research objects, workflows.

On OpenAIRE side, we are already collecting from bio.tools API and we are considering the metadata to be descriptions of software. If you think that's correct, then you should use the software guideline. The guidelines for software and other products are not yet finalised and we welcome feedback and suggestion, so feel free to open issues on the relative github project (you'll find the link at the top of the guideline pages) or write to me and @mirima2.

**Comment by joncison** [comment]
OK .. thanks a a lot for the clarification.  Software Guidelines look good, but I'll get back on a  few points soon.

**Comment by joncison** [comment]
**UPDATE** 
* SPDX (The Software Package Data Exchange) specification is a standard format for communicating the components, licenses and copyrights associated with a software package
http://spdx.org/
-> *biotoolsSchema* captures the SPDX vocabulary precisely in the ``<license>`` enum

* HCLS (Dataset Descriptions: from Semantic Web in Health Care and Life Sciences Interest Group)
http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/#s4_1
-> mapped, see https://github.com/bio-tools/biotoolsSchema/issues/122

* W3CPROV (provenance information)
https://www.w3.org/TR/prov-overview/
-> mapped, and will be taken forward via [biotoolsRDF](https://github.com/bio-tools/biotoolsRdf)

* OntoSoft
http://ontosoft.org/ontology/software/
-> mapped, see https://github.com/bio-tools/biotoolsSchema/issues/120

* RFC standard for describing URL templates (URL scheme)
https://tools.ietf.org/html/rfc6570
(see also https://support.google.com/webmasters/answer/6080550?hl=en)
-> *todo*, see https://github.com/bio-tools/biotoolsSchema/issues/125

* schema.org
http://www.schema.org/docs/extension.html
-> mapped (via CodeMeta), see https://github.com/bio-tools/biotoolsSchema/issues/113

biodbcore
http://database.oxfordjournals.org/content/2011/baq027.full
-> mapped, see https://github.com/bio-tools/biotoolsSchema/issues/126

GA4GH tool registry schema
https://github.com/ga4gh/tool-registry-schemas/
-> mapped, see https://github.com/bio-tools/biotoolsSchema/issues/127

re3data.org Schema for the Description of Research Data Repositories
https://blog.datacite.org/new-re3data-schema-and-search-functionality/
-> mappped, see https://github.com/bio-tools/biotoolsSchema/issues/117 

closing this cc @matuskalas
