### ISSUE TITLE
Consider deprecating "Browser" as type of link

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#130]
at least I'm not sure what we meant by "A website for browsing data." as the justification for ``<link><type>Browser</type></link>``.  @matuskalas can you clarify / do you have an opinion?

**Comment by jlgelpi** [comment]
Having a place for borwsing/searching data is required for publishing any database, so I would call it rather "Data portal" or "Database Portal", although it should be the main url when registering databases.

**Comment by joncison** [comment]
this is dropped in biotoolsSchema 3.1.0
