### ISSUE TITLE
license enum has "Unlicense" and "Unlicensed"

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsSchema#136]
I think the "Unlicense" should be removed and, if there are tools with this, change to "Unlicensed".

D.

**Comment by hansioan** [comment]
@redmitry 
'Unlicense' is an actual license:
http://unlicense.org/

whereas 'Unlicensed' means the tool has no license.

**Comment by redmitry** [comment]
Oh!
Thank you for the explanation.
D.
