### ISSUE TITLE
ORCID iD syntax regex is too restrictive

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsSchema#142]
The restriction pattern for `"orcidid"` is currently specified as
`<xs:pattern value="http(s?)://orcid.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}"/>`

Turns out, that the last character of a valid ORCID can also be "X", representing the value "10". Which means, that such ORCID iDs can't currently be inserted into bio.tools.

A few random such IDs:
http://orcid.org/0000-0002-2556-537X
http://orcid.org/0000-0002-7054-800X
http://orcid.org/0000-0003-2715-335X

**Comment by jaanisoe** [comment]
The dot could also be escaped as `orcid\.org` (https://github.com/bio-tools/biotoolsSchema/issues/124)

**Comment by joncison** [comment]
thanks! 

will make a minor release of biotoolsSchema before the Summer, so please keep these sorts of suggestions coming.  I'll incorporate all of them in one hit.

**Comment by joncison** [comment]
@jaanisoe fixed, the pattern - which now drops the URL prefix - is simply 

```[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]```
