### ISSUE TITLE
ORCID id syntax ... drop the URL bit !

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#144]
which is obv. not part of the IDs

see https://github.com/bio-tools/biotoolsRegistry/issues/437

**Comment by hansioan** [comment]
I don't know... the orcid.org website looks like they want urls in the id:

https://orcid.org/news/2012/08/02/what-does-orcid-identifier-look-like
https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

**Comment by joncison** [comment]
Yup ... I was wrong in my OP, will have to revert the change in 3.1.0 (which is now bugged :) )
