### ISSUE TITLE
Some incomplete fixes in 3.1.0

### ISSUE THREAD

**Issue by jaanisoe** [bio-tools/biotoolsSchema#148]
The dot metacharacter should be escaped in patterns when only a period is meant #124

The `.` is still unescaped in:

`<xs:pattern value="http://edamontology.org/topic_[0-9]{4}"/>`
`<xs:pattern value="http://edamontology.org/format_[0-9]{4}"/>`
`<xs:pattern value="https://orcid.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]"/>`
`<xs:pattern value="10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+"/>`

---

Add Julia Language #103

Julia was accidentally added to the list of licenses instead. In a recent commit made after 3.1.0 (5daa96fbb1cb6e34c34207e37289a2374a071e6d), Julia was correctly added to the list of languages, but it still should be removed from the list of licenses:

```xml
...
<xs:enumeration value="Intel-ACPI"/>
<xs:enumeration value="Interbase-1.0"/>
<xs:enumeration value="Julia"/>
<xs:enumeration value="JSON"/>
<xs:enumeration value="JasPer-2.0"/>
<xs:enumeration value="LAL-1.2"/>
<xs:enumeration value="LAL-1.3"/>
<xs:enumeration value="LGPL-2.0"/>
...
```

---

ORCID iD syntax regex is too restrictive #142
ORCID id syntax ... drop the URL bit ! #144

Currently, an ORCID iD in bio.tools must begin with "https://", although it seems that ORCIDs are often listed with "http://" and that version with the HTTP protocol also seems to work (without redirecting to HTTPS). So should "http://" also be allowed in addition to "https://" (although I guess HTTPS links should be preferred)?

---

doi syntax regex is too restrictive #8

In 3.1.0:

```xml
<xs:restriction base="xs:token">
	<xs:pattern value="10\.[0-9]{4,9}/[A-Za-z0-9:;\)\(_/.-]+"/>
	<xs:pattern value="10\.[0-9]{4,9}/[\[\]&lt;&gt;A-Za-z0-9:;\)\(_/.-]+"/>
</xs:restriction>
```

The second pattern seems to include the first, so can the first pattern be safely removed?

---

In the DOI pattern under `"otherID"`:

`<xs:pattern value="10.[0-9]{4,9}[A-Za-z0-9:;\)\(_/.-]+"/>`

The `/` character could be added after `{4,9}`.

**Comment by joncison** [comment]
thanks @jaanisoe ... excellent.  All fixed along lines suggested:
* \.\ symbol now escaped
* *Julia* language removed from license
* **orcidID** syntax now supports `http://` prefix
** **doi** syntax now consistent, using long pattern only (in both **otherID->value** and **publication->doi**

cc @hansioan - pls. add these fixes to your list
