### ISSUE TITLE
Add tool type of "Bioinformatics platform" (or "Bioinformatics portal")

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#149]
With definition of something like ...
_"A web site providing a portal to multiple resources providing a platform for research in a focused area, including biological database, web applications, training resources and so on."_

For reference, see the [other tool types](https://biotoolsschema.readthedocs.io/en/latest/controlled_vocabularies.html#tool-type)

Such sites can have their issues, but there are lots of them out there (including in the ELIXIR FR SDP).

cc @hansioan @hmenager

**Comment by hansioan** [comment]
@joncison @hmenager 
The definition still needs a bit of work I think, improving a bit on it would be:
_"A web site providing a platform/portal to multiple resources used for research in a focused area, including biological databases, web applications, training resources and so on."_

**Comment by joncison** [comment]
Better, thanks!  

Are you happy with this @hmenager ?  NB:  This term is for describing some of the things submitted to the ELIXIR FR SDP, _not_ the official IFB "platforms" (although some of them probably have to a platform as defined).

**Comment by joncison** [comment]
[IFB Guidelines ](https://biotools.readthedocs.io/en/latest/IFB_tools.html) go with "Bioinformatics portal" as per latest definition.
