### ISSUE TITLE
Tweak definition of "Database portal" tool type

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#150]
Currently "Database portal" is [defined ](https://biotoolsschema.readthedocs.io/en/latest/controlled_vocabularies.html#tool-type) as _"A Web application, suite or workbench providing a portal to a biological database."_

But such portals are invariably web sites - often with common functionality - and mentioning suites and workbenches is just confusing.  

So, for easier comprehension, something like _"A Web site providing a portal to a biological database, typically allowing a user to deposit, search, visualise, analyse or download data."_

cc @hansioan @hmenager - what do you think?

**Comment by hansioan** [comment]
@joncison I agree, the second definition is  better.

**Comment by joncison** [comment]
ta.  and should add "Browse" too
