### ISSUE TITLE
Change definition of "Service" in <link><type> enum

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#153]
Now we have "Galaxy service", "Service" should be redefined, something like: _"An online service (other than Galaxy) that provides access (an interface) to the software."_

**Comment by hansioan** [comment]
@joncison We need to be careful so that we don't redefine the concept of an API / web service. Do you have any examples of such a "Service" other than Galaxy?

**Comment by joncison** [comment]
Agree.  I think "Service" was originally intended for (now clearer) "Galaxy service" but could, in principle, be any web site serving that tool?  So it could be useful where we have say a command-line tool being dished up in multiple places (but with essentially the same functionality)?

**Comment by joncison** [comment]
@hansioan let's talk later today, but I think it's likely essential, if we're to achieve functionally unique entries.  Could rename to *Online service* to make meaning clearer.  I think we have lots of content here (from the big clean-up of redundant entries we did) ... need to check whether in fact they were all just *Galaxy service*, or others.  Then decide. 

cc @matuskalas @hmenager

**Comment by joncison** [comment]
For now, leave as-is, but with new definition _"An online service (other than Galaxy) that provides access (an interface) to the software."_
