### ISSUE TITLE
Consider refactoring license, cost, accessibility

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsSchema#154]
@matuskalas says these can be reduced and made clearer. Let's discuss here @joncison @hmenager

**Comment by joncison** [comment]
I propose:
- leave the definition of [cost ](https://biotoolsschema.readthedocs.io/en/latest/controlled_vocabularies.html#cost) as it is - I don't see what's wrong with it.
- just remove *Proprietary* and *Freeware* which conflate with **License** (see below) and confuse the meaning of accessibility quite badly.  If we did this, **Accessibility** simply becomes a choice between *Open access* and *Restricted access* (applicable to online services only) which is very clear
- leave [License](https://biotools.readthedocs.io/en/latest/curators_guide.html#license) as it is.  There is *Proprietary*, *Unlicensed* and *Other* but I think they all serve a purpose.  PS.  we've used "Unlicensed" quite a lot where we searched for a license, but one does not exist.

cc @hansioan @matuskalas @hmenager

**Comment by joncison** [comment]
Done in 3.2.0: removed from *accessibility* the terms *Proprietary* and *Freeware*

**Comment by joncison** [comment]
NB: cardinality set to *0 or 1* (was *0 to many*) given there's now a choice between two mutually exclusive things.
