### ISSUE TITLE
Consider deprecating link[@type='registry']

### ISSUE THREAD

**Issue by hmenager** [bio-tools/biotoolsSchema#156]
they are redundant with `otherID` element

**Comment by joncison** [comment]
I agree, and it's not clear what *Registry* is.

But this would mean a refactor.  *otherID* currently supports (via regex) DOIs, RRIDs, cpe identifiers and *bio.tools* toolIDs (to allow multiple IDs for single entry, should that in edge-cases be strictly necessary).

Would be easy enough to add support for URLs as a valid ID syntax, then move the existing values over.

Thoughts @hansioan @matuskalas @hmenager

**Comment by joncison** [comment]
Action taken was to rename this to _"Software catalogue"_ which is easier to understand, and better.  Had quite a lot of data for this, but not all the links to thins that are really registries.  Can't be moved to **otherID** because the these URLs are not identifiers in the strict sense.
