### ISSUE TITLE
Link to Bioconda packages

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#158]
Hi @bgruening 

We we're discussing today whether it makes sense for biotoolsSchema hence *bio.tools* to support links somehow to conda packages (and this also with view to future "ecosystem"). Would that be useful, if so, what to link to?

*e.g.* 
* to the package metadata / description *e.g.* https://anaconda.org/bioconda/phate
* to the package download *e.g.* https://anaconda.org/bioconda/phate/0.4.5/download/noarch/phate-0.4.5-py_0.tar.bz2
* link to the conda recipe *e.g.* https://github.com/conda/conda-recipes/tree/master/3proxy

or something else?

please advise -thanks !  cc @hansioan @matuskalas @hmenager

**Comment by bgruening** [comment]
Will be at the BH in a few hours looking forward to talking to you about all this very soon :)

Initial thoughts is that 1 makes sense, as one also containers 3 in the tarball.

**Comment by matuskalas** [comment]
After a check with bg & an3, I confirm that the link should be _e.g._

* https://bioconda.github.io/recipes/bowtie2/README.html

in general

* `https://bioconda.github.io/recipes/<packagename>/README.html`

and it should be called _Package (Bioconda)_ (or _Package (Conda)_?). See also #164

**Comment by joncison** [comment]
For now, the way to handle this is done (see https://github.com/bio-tools/biotoolsSchema/issues/164).  So no action needed for now.

**Comment by joncison** [comment]
This thread taken up in https://github.com/bio-tools/biotoolsSchema/issues/164
