### ISSUE TITLE
Attributes specific for simple "collections" of other tools (from GO import)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#16]
The GO tools collection :
https://docs.google.com/spreadsheets/d/1-Gu6EhBXTDr35vOU2MwUVOzGAWXTAkIdARdad9UShRw/edit#gid=1268003428

These are officially "GO approved" tools and we need to annotate them as such.  This is an attribute of the "collection" per se, and not the tools, thus a new attribute is needed. 

Consider closely what other collection-specific attributes are required.

**Comment by veitveit** [comment]
I could take a look on them if necessary

2016-02-29 11:13 GMT+01:00 Jon Ison <notifications@github.com>:

> The GO tools collection :
>
> https://docs.google.com/spreadsheets/d/1-Gu6EhBXTDr35vOU2MwUVOzGAWXTAkIdARdad9UShRw/edit#gid=1268003428
>
> These are officially "GO approved" tools and we need to annotate them as
> such. This is an attribute of the "collection" per se, and not the tools,
> thus a new attribute is needed.
>
> Consider closely what other collection-specific attributes are required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bio-tools/biotoolsxsd/issues/16>.
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
Thanks, but I think what's needed is a generic XSL->XML transform.  I have a few which were custom jobs, but we need to settle on a stable "spreadsheet format" and thus, the transform can be stable too.  So I think this can wait until biotoolsXSD 2.0, where everything will change ...

**Comment by joncison** [comment]
done in biotools-2.0-beta01

this will be handled by <collection> element, i.e. a valid bio.tools collection ID.  Support for collections in bio.tools is not yet ready, but so far as biotoolsXSD goes the issue can be closed.
