### ISSUE TITLE
Multiple "tags" for one link

### ISSUE THREAD

**Issue by hmenager** [bio-tools/biotoolsSchema#163]
A nice way to avoid copy & pasting of links, would be having one link annotated by multiple **types of link**, just like publications are.

Example: http://blahbl.ah/README containing Installation instructions, attribution instructions, etc.

(btw., this issue was written by @matuskalas)

**Comment by joncison** [comment]
Massive thumbs up from me, because this reflects reality and simplifies curation process.

cc @hansioan

**Comment by joncison** [comment]
cardinality was *1 only* now is *1 to many*
