### ISSUE TITLE
Remove "note" from Credit

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#169]
This is just far beyond bio.tools scope to include such fine-grained attribution information.

**Comment by joncison** [comment]
This has been filled for 239, so keep this for now.

**Comment by matuskalas** [comment]
What do you mean here @joncison ?

**Comment by matuskalas** [comment]
If, then we could consider one **"note"** for the whole of Credits, but not for each Credit item.

**Comment by joncison** [comment]
The current status is that a note (any arbitrary comment) can be assigned to each credit.  This OK for now.
