### ISSUE TITLE
Add support for organisational IDs

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#172]
Just GRID IDs for now, but could also be ROR.

GRID IDs was supported in biotoolsSchema 2..0.0

**Comment by joncison** [comment]
sample value:
grid.5170.3

**Comment by matuskalas** [comment]
In addition to GRID IDs, should also be DOIs (for funders), Ringgold IDs, and the ROR IDs.

+keeping an eye on the ongoing developments of the organisation ID initiative from ORCID+DataCite+CrossRef+etc.:
* https://orcid.org/content/2018-org-id-meeting
* https://orcid.org/content/organization-identifier-working-group
* https://orcid.org/blog/2018/02/02/next-steps-organization-id-initiative-report-stakeholder-meeting

**Comment by joncison** [comment]
Yes, and also FundRef IDs, see https://github.com/bio-tools/biotoolsSchema/issues/114

For now, *credit->gridId* added.

I'm convinced (given many ID types) this will be better handled by replacing **gridId**, **orcidId** *etc.* with:
* **credit->Id**
* **credit->Id->value**
* **credit->Id->type**

*i.e.* as per the pattern used elsewhere
