### ISSUE TITLE
Change "Unlicensed" to "Not licensed" in License enum

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#173]
Because this is super-confusing with the official *Unlicense* license

**Comment by matuskalas** [comment]
Probably better **"No license"**

Or maybe even better to consider merging with _Proprietary license_ to improve **searchability and filtering** (even if the 2 are formally different, they have the same outcome in practice; and if separate, annotators are prone to choose one of the 2 at random):
 * "No or proprietary license"
 * "None or proprietary license"
 * "No license / Proprietary"
 * "No license / Proprietary license"

What do you think? CC @hmenager We can also ask the Debian and 4OSS folks for advice...

2019-11-21, to explore the confusion:
* "Proprietary" (34 records) : https://bio.tools/t?page=1&license=%27Proprietary%27&sort=score
* "Unlicensed" (88 records) : https://bio.tools/t?page=1&license=%27Unlicensed%27&sort=score

**Comment by joncison** [comment]
For now @matuskalas *Unlicensed* changed to *Not licensed* (arguably a bit more explicit than *No license*), with view to future revision as needed (I quite like your last suggestions for reason you give above)
