### ISSUE TITLE
Additional properties that are not specified in the "tool" Json Schema.

### ISSUE THREAD

**Issue by vsundesha** [bio-tools/biotoolsSchema#194]
Hello,

The data provided by the Biotools tools API has additional properties that are not specified in the Json Schema defined for the "tool" definition.
 
For example:
This tool https://bio.tools/api/tool/broccoli has fields ("validated", "confidence_flag", etc..) which do not show up in the Json Schema https://github.com/bio-tools/biotoolsSchema/blob/master/json/biotools.json

I understand that the data is validated on your side before being injected into the database. The issue is that Json Schema has a property called "additionalProperties" https://json-schema.org/understanding-json-schema/reference/object.html#properties which by default is set to "true". This allows properties to be added apart from the ones defined by the Json Schema.

Could some these additionalProperties like for example "validated" be added as a standard properties to the "tool" schema?

Thank you!

**Comment by joncison** [comment]
Hi, and thanks for the interest. The focus of biotoolsSchema (on tools _per se_) is intentional, and this means that _bio.tools_-specific "housekeeping" metadata is excluded.  But @hansioan and I will discuss it - could you please elaborate which properties you're interested in and why?  Cheers!

**Comment by joncison** [comment]
Closing this for now, feel free to reopen @vsundesha if you can get back to us as per thread above.  Thanks.  cc @hansioan
