### ISSUE TITLE
Add EPL-2.0 as license

### ISSUE THREAD

**Issue by Kigaard** [bio-tools/biotoolsSchema#204]
It would be nice, if version 2.0 of the Eclipse Public License (EPL. https://spdx.org/licenses/EPL-2.0.html) could be added as an option. Version 1.0 is available option (https://spdx.org/licenses/EPL-1.0.html).

-Mads

**Comment by matuskalas** [comment]
Nice, thanks for spotting it @Kigaard👍🏽 Have you seen also some concrete tools that use EPL-2.0?

Do you feel like forking the repo, adding it into a new branch, and issuing a pull request? If yes, but need help, please ask and one of us maintainers will gladly help you👍🏽

**Comment by Kigaard** [comment]
Not on top of my head – I wrote it down a while ago.

I would happily try but I have not worked that much with active side of contribution so to speak 😅 It is mostly the adding to branch and pull request stuff I am a little worried about, and I don't want to be an inconvenience
