### ISSUE TITLE
Add Visual C++ as language?

### ISSUE THREAD

**Issue by veitveit** [bio-tools/biotoolsSchema#25]
It is not a language by itself (C++ is) but it can be very helpful that a program was not implemented in pure C++

**Comment by magnuspalmblad** [comment]
Yes, I know .NET is not a language, but I used in the annotations as I thought it may be helpful to people developing in the .NET framework.

Do we want to add a field for "library" or "framework" to the annotations?

**Comment by matuskalas** [comment]
Re @magnuspalmblad ("Do we want to add a field for "library" or "framework" to the annotations?"):

Yes, I think that may be useful. A __dependency__ (or a _major dependency_) in general. Could work as "free tags", with suggesting the registrants and curators the "tags" that have been used already.

However, when a dependency is a bioinformatics tool, it should sooner or later be properly registered in Bio.Tools and linked accordingly.

But I still think that _execution platforms_ proper - including .NET - should perhaps rather be platforms (with Qt, Java, Python, X Windows, WWW, POSIX or Linux or so, etc...). Perhaps not _implementations_ of the execution platforms, but _"standards"_.

__NB.__ This issue should be merged with #23.

**Comment by matuskalas** [comment]
Another thought: In addition to a "free tag", a __dependency__  could also allow and support IDs/links such as Debian packages, Free Software Foundation's Directory entries, Wikipedia sites, or such...

**Comment by veitveit** [comment]
One could build a hierarchy built upon interfaceType, resourceType and
language, making it more straightforward to choose only the options that
make sense.

A "free tag" (if I understood that correctly) can help to let this
hierarchy kind of autogenerate, by curators/registrants adding tags that
they seem appropriate and missing.

2016-04-18 19:51 GMT+02:00 Matúš Kalaš <notifications@github.com>:

> Another thought: In addition to a "free tag", a *dependency* could also
> allow and support IDs/links such as Debian packages, Free Software
> Foundation's Directory entries, Wikipedia sites, or such...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bio-tools/biotoolsxsd/issues/25#issuecomment-211500340>
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
I think that (hierarchy) could be interesting especially to help us define what we mean by the corresponding terms - also valuable if the bio.tools registration interface goes ahead and makes use of it (i.e. type-specific registration interface).

It'd be beyond the expressivity of XSD to encode it as constraints though (at least, in a simple schema)

**Comment by veitveit** [comment]
Actually, there is also the tag _platform_ in bio.tools XSD. This is a bit confusing and calling it _operation system_ is more appropriate. 

About the hierarchy, wouldn't that be a nice addition to the Tool Annotator?

**Comment by joncison** [comment]
The Tool Annotators is mostly focused on EDAM annotation so it's out of scope BUT it will sit within a (revamped) registration interface - which could make use of such a hierarchy.  Actually, this issue has come up before:
https://github.com/bio-tools/biotoolsregistry/issues/54

**Comment by joncison** [comment]
Folks, for now (in the impending 1.5 release for msutils.org) I'm leaving frameworks and IDEs out; with bio.tools, we have to draw the line somewhere.  Can always revisit this in 2.0

**Comment by magnuspalmblad** [comment]
Agree! It is best to focus on the tools that can easily be integrated in workflows and play well with other tools. Some of the GUI-based software can perform a wide range of operations, but may not necessarily produce output in some well-defined format. The "frameworks" that are code libraries are perhaps better described as "tools for making tools", rather than tools for analyzing mass spectrometry data.
