### ISSUE TITLE
Add Proprietary license to licenses

### ISSUE THREAD

**Issue by veitveit** [bio-tools/biotoolsSchema#27]
Such a term would include e.g. commercial licenses

**Comment by matuskalas** [comment]
It should then perhaps be called just _Proprietary_ and be distinguished so that it's not alphabetically sorted among the open-source/free-software licenses.

But the question is whether that makes sense.

Another questions is whether Cost and License should anyhow be integrated or even merged. With a bit of a hierarchy then.

Another important distinction is between **software** and a **service**, where matters of cost, license, terms of use, commerce, _etc._ apply differentially (see also https://github.com/bio-tools/biotoolsregistry/issues/54)

**Comment by veitveit** [comment]
Agreed. Can a *Proprietary* term be excluded from the sorting in the xsd
terminology?

I slowly get to the impression that we'll have to decide whether to
interconnect many of the different tags (costs, software, platform,
license, ...) by generating a hierarchy.

As a short-term solution, can we decide to include a *Proprietary* licence?

2016-04-28 14:06 GMT+02:00 Matúš Kalaš <notifications@github.com>:

> It should then perhaps be called just *Proprietary* and be distinguished
> so that it's not alphabetically sorted among the open-source/free-software
> licenses.
>
> But the question is whether that makes sense.
>
> Another questions is whether Cost and License should anyhow be integrated
> or even merged. With a bit of a hierarchy then.
>
> Another important distinction is between *software* and a *service*,
> where matters of cost, license, terms of use, commerce, *etc.* apply
> differentially (see also bio-tools/biotoolsregistry#54
> <https://github.com/bio-tools/biotoolsregistry/issues/54>)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bio-tools/biotoolsxsd/issues/27#issuecomment-215403205>
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
Actually "Custom" may be much better than "Proprietary" (at least for the msutils.org licenes, SFAIK) as it doesn't have any of the implications of exclusivity that the latter does.

**Comment by matuskalas** [comment]
But "Custom" does not say anything, thus it's the same as leaving the attribute blank.

Whereas "Proprietary" means it needs to be obtained from the provider (_e.g._ for money), and then owned. So definitely not open-source or free software. But may or may not be commercial.

**Comment by joncison** [comment]
Well, "Custom" says the software is available under some bespoke license, as distinct from being unlicensed (== bad) , or simply not specified (no annotation).  Thus this tag would be usefully informative.

**Comment by veitveit** [comment]
Interesting discussion :-)
*Proprietary licence* seems to be a quite common term, hence I would prefer
it.
BUT: *custom* could still be used for the rest, e.g. the ones not covered
by the already quite extensive list in bio.tools

2016-05-02 17:16 GMT+02:00 Jon Ison <notifications@github.com>:

> Well, "Custom" says the software is available under some bespoke license,
> as distinct from being unlicensed (== bad) , or simply not specified (no
> annotation). Thus this tag would be usefully informative.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bio-tools/biotoolsxsd/issues/27#issuecomment-216264351>
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by matuskalas** [comment]
Re @veitveit:

_Proprietary license_ or _Proprietary_: :+1: 
But if including the word _license_ then it should be _license**s**_, otherwise it doesn't compute! ;-)

If you want something like "Custom", then it should be _Other_, because:
1. There are other licenses that aren't "custom".
2. Proprietary licenses are usually "custom".
But a more ontological approach, with a hierarchy, would be __much__ more useful.

**Comment by veitveit** [comment]
All ok for me :-), with preference on *Proprietary* excluding the license.

A hierarchical approach is definitely better, but I don't know whether it
is worth the work, additionally thinking about how to include a term
hierarchy into bio.tools annotation.


2016-05-03 12:12 GMT+02:00 Matúš Kalaš <notifications@github.com>:

> Re @veitveit <https://github.com/veitveit>:
>
> *Proprietary license* or *Proprietary*: [image: :+1:]
> But if including the word *license* then it should be *licenses*,
> otherwise it doesn't compute! ;-)
>
> If you want something like "Custom", then it should be *Other*, because:
> 1. There are other licenses that aren't "custom".
> 2. Proprietary licenses are usually "custom".
> But a more ontological approach, with a hierarchy, would be *much* more
> useful.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bio-tools/biotoolsxsd/issues/27#issuecomment-216487429>
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by matuskalas** [comment]
And among the __"Cost"__ options, we should perhaps add something like **_For free, with commercial interest_** and **_Free option_**. _I.e._ to distinguish the models of _e.g._ Google from GitHub, and from completely non-commercial services.

And  in addition instruct the annotators / curators of services, to select an applicable __License__, if the software of the web application is available for download (with or without **source code**).

**Comment by joncison** [comment]
Folks, I'm creating biotools 1.5 to provide a fix for various things, before we move to 2.0

It will include in "license" enum the following terms:

"Other"
"Proprietary"

and we revisit this and all other things in due course, in 2.0
