### ISSUE TITLE
Rename to "bio.tools.Schema" or so, to avoid tech choice lock

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#29]
Should be acted upon asap (before 2.0), not to repeat the mistake of BioXSD, not to get stuck with XSD in the name forever.

_E.g._ although XSD 1.1 is better and more expressive than 1.0, JSON Schema may be even more expressive. And even better schema languages may appear whenever, without warning ;-)

**Comment by hmenager** [comment]
+1!

**Comment by joncison** [comment]
Agree.  And for various reasons I propose "biotools core" shorthand for "bio.tools core schema"

**Comment by joncison** [comment]
So this will be biotoolsSchema cc @hmenager, once I finish my edits on 2.0-beta02 (tonight !)
