### ISSUE TITLE
Deprecate "Infrastructure", use "Collection"

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#3]
As a quick fix.

(In addition will work awesomely after adding edamontology/edamontology#40)

For the further future, consider registering collections as separate "resource types", with various properties (now only name) available for filling in.

**Comment by joncison** [comment]
done in 2.0-beta02 (infrastructure is gone, although "Consortium" et al can be specified as a type of creditable entity (in < credit -> entity > element)

collections per se will be handled in bio.tools, but you can still assign tools to a collection in XML via < collection > element (the value is supposed to be a bio.tools collectionID)
