### ISSUE TITLE
Add "R" as an interfaceType

### ISSUE THREAD

**Issue by bug1303** [bio-tools/biotoolsSchema#30]
I could see that most of the bioconductor packages in bio.tools are annotated with
resourceType: Tool
interfaceType: Command line

Some other R packages however have:
resourceType: Library
interfaceType: API

I understand that these terms should be rather broad and only a few of them in the enumeration, however I think it would make sense to add something more specific here. What is an R package really? I could see the definition of "Command line : Text-based interface to a tool or service", which is of course also true for R, but many researchers that use R, do so in a semi-graphical interface and some of them are scared off by 'actual' command lines. I think being able to explicitly search for R packages will help those having a better user experience.

**Comment by joncison** [comment]
Thanks - good point well made.  There will be big changes to interface and resource type in biotoolsXSD 2.0, also to bio.tools, which will address this (watch this space).

**Comment by matuskalas** [comment]
A correct record about an R package should state Tool, API::Library, Language: R, and have links to the corresponding packages in a package repo (typically CRAN or Bioconductor). The links to packages I hope will be nicely supported in 2.0, as decided in the May meeting in Paris.

**Comment by joncison** [comment]
done in biotools-2.0-beta01

"R" is now in <language> enum
