### ISSUE TITLE
Support NCBI taxon ID

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#31]
For ideas on how, see:
https://github.com/bio-tools/biotoolsregistry/issues/104

**Comment by matuskalas** [comment]
To my knowledge, a nice way of dealing with taxons is _e.g._ in the [ELM database](http://elm.eu.org/) (although they don't visualise it in any great way), with inclusive and exclusive taxon trees, _i.e._ a list of 0 or more positive taxons (ones that apply) and a list of 1 or more negative taxons (ones that don't apply even if their ancestors do apply). That means that the negative taxons (_i.e._ trees) are subtracted from the positive taxons (trees).

**Comment by joncison** [comment]
If supporting just a subset, this would be a good place to start:
http://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/

Plus maybe some high-level IDs

**Comment by joncison** [comment]
See http://www.nmpdr.org/FIG/wiki/view.cgi/FIG/TaxonomyIdentifier

**Comment by joncison** [comment]
done in biotools-2.0-beta01

currently not restricting to any taxID subset
