### ISSUE TITLE
Support for organisational IDs

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#35]
(for all the same good reasons as supporting ORCIDs)

The best we have may be Ringgold IDs from openidentify.com but they seem to have no API or access to data.  ORCID are using / working with them though, see:
http://support.orcid.org/knowledgebase/articles/276884-how-are-organizations-identified-in-orcid

**Comment by joncison** [comment]
Or for a modern solution with open access to data, GRID.ac IDs look good
https://www.grid.ac/

**Comment by IanCal** [comment]
Happy to answer questions on GRID if it helps (I'm one of the data scientists on the team) :)

**Comment by joncison** [comment]
Thanks!  

What is the syntax for a valid grid ID ?  I need a XSD regex to support it in biotoolsXSD.

**Comment by IanCal** [comment]
The regex we use is:
     /grid\.[0-9]+\.[a-f0-9]{1,2}/i 

That is, it's

    grid.

Then numerical digits (there are always at least 4 and there's technically no upper limit but currently varies between 4 and 6).

Then another period

Then one or two hex chars

All ids are lowercase, however we try and deal with people who pass through uppercase versions. I'd recommend being able to identify ids even if they're uppercase, but always storing them lowercase.

**Comment by joncison** [comment]
Super - thanks !

done in biotools-2.0-beta01

**Comment by IanCal** [comment]
That is some speedy work!
