### ISSUE TITLE
Support virtual machine images

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#36]
This has often been requested

We want a link to the image (or a repo) with light-weight metadata, i..e *not* everything listed here:
http://docs.openstack.org/image-guide/image-metadata.html

Maybe just the disk and container format?

**Comment by matuskalas** [comment]
Would it be enough to support URL links to VM images?

It should perhaps be done in exactly the same way as supporting software containers, _i.e. e.g._ via links to [BioShaDock](https://docker-ui.genouest.org/) (https://github.com/osallou/bioshadock), but not limited to those.

The https://github.com/bio-tools/biotoolsregistry could even recognise some major repositories (_i.e. e.g._ the [BioShaDock](https://docker-ui.genouest.org/)) and show basic information pulled from there.

**Comment by joncison** [comment]
Not quite, I think we also need to support annotation of the image / container format.  At least, doing so would be super-useful at low cost.  For the rest of the data, I agree bio.tool can pull that from whatever repo.

**Comment by matuskalas** [comment]
I agree.

Then we need to collate a tiny "ontology" of VM-image and SW-container formats/platforms. Perhaps some virtualisation and container geek(s) with a broad overview could help. What about coming up with something to start with first, and then refine it for example at the next Tools|Workflows|Workbenches hackathon, tentatively in January 2017?

**Comment by joncison** [comment]
Cool  ...  there'll be something in v2.beta of the schema  (and that out soon!)

**Comment by joncison** [comment]
done in biotools-2.0-beta01
