### ISSUE TITLE
Support (links to) tool wrappers

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#37]
e.g. CWL file, Galaxy tool confiig file etc.

For list see:
https://en.wikipedia.org/wiki/Bioinformatics_workflow_management_system

Also see:
http://bib.oxfordjournals.org/content/early/2016/03/23/bib.bbw020.full

**Comment by matuskalas** [comment]
:+1:

**Comment by joncison** [comment]
done in biotools-2.0-beta01
