### ISSUE TITLE
Support basic HTTP API spec

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#39]
Including URL template (https://en.wikipedia.org/wiki/URL_Template) and endpoints

**Comment by matuskalas** [comment]
:+1: 
And in addition, we should allow including URL links to WSDLs, JSON Schemata, WADLs, etc.

**Comment by joncison** [comment]
Agreed.  Am I right to assume bio.tools can infer the type of API spec file from it's file extension? 

In any case, we could add an optional <comment> field, to allow this to be clarified (or for other misc. comments).

Good idea?

**Comment by matuskalas** [comment]
:+1: 

A separate field would be good, as a file extension isn't trustworthy enough, and may not be present at all.

**Comment by joncison** [comment]
done in biotools-2.0-beta01

**Comment by joncison** [comment]
Tho
