### ISSUE TITLE
Add a Docker registry link

### ISSUE THREAD

**Issue by osallou** [bio-tools/biotoolsSchema#4]
Get possibility to insert a Docker registry url for the tool, example:

docker-registry.genouest.org/bioinfo/blast  (meaning version latest)

or with a version tag

docker-registry.genouest.org/bioinfo/blast:1.0

with this, user only needs to do a 

    docker pull *docker_url*

Schema could support multiple Docker registries urls

**Comment by joncison** [comment]
release is out ; if it doesn't do what you want @osallou  ,pls. re-open with more requirements
