### ISSUE TITLE
xs:documentation source attribute must contain an URI

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsSchema#42]
In beta1:

line 91:
<xs:element name="biotoolsId" type="biotoolsIdType">
  <xs:annotation>
    <xs:documentation source="The ID is a URL in the bio.tools namespace and reflects (normally exactly) the tool name and version: see http://biotools.readthedocs.io/.">Unique ID that is assigned upon registration of the software in bio.tools.  </xs:documentation>

line 112:
<xs:element name="shortDescription">
  <xs:annotation>
    <xs:documentation source="A single declarative sentence in the present tense, providing a terse statement of the tool function.  State what is done, i.e.operation, and primary inputs and outputs, but not how. Do not include tool name. See http://biotools.readthedocs.io/.">Short and concise textual description of the software function.</xs:documentation>

**Comment by joncison** [comment]
well spotted!

fixed in 2.0-beta-02
