### ISSUE TITLE
urlftpType could hold http(s) ?

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsSchema#43]
there is an urlftpType that restricts anyURL to the either http(s) or (s)ftp (???).
on the other hand urlType is restricted to the http(s).
something is wrong here... 
remove http(s) from urlftpType and rename urlType into urlhttpType. (???)

**Comment by joncison** [comment]
thanks!  will do ... and please keep the review coming (very helpful)

**Comment by joncison** [comment]
@redmitry  urlftpType is supposed to be http(s) OR  (s)ftp   whereas urlType does not support (s)ftp.  So I think this is OK?

**Comment by redmitry** [comment]
I am just confused how url_FTP_type could hold an https URL.

**Comment by joncison** [comment]
I added documentation in xs:annotation to clarify the meaning here
