### ISSUE TITLE
Improve functionality mentioned in Artaza et al. 2016

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#48]
Hooray, [Artaza _et al._ 2016](http://f1000research.com/articles/5-2000/v1) ([10.12688/f1000research.9206.1](http://doi.org/10.12688/f1000research.9206.1)) voted software "discoverability", including [Bio.Tools](http://bio.tools) registration, as the **2nd most important** factor of good practices :+1: :+1: :+1: 

We should make sure that other mentioned factors and requirements _ibid._ - other than just bare registration - are well and soon supported too, where applicable.

**Comment by joncison** [comment]
absolutely : should review the metrics, see what can be modelled in biotoolsXSD and how it can be used in bio.tools.  I'm discussing this (amongst others) with ELIXIR Hub in Sep ...

**Comment by joncison** [comment]
This also tracked in https://biotools.sifterapp.com/issues/192 

Leave this open till more progress is made.

**Comment by joncison** [comment]
So I've been through the article and in beta03 (out very soon) everything that is easily modeled and is maintainable is included.   I'm not sure about other attributes listed, which are no doubt important, but are more in scope of ELIXIR EXCELERATE WP2 (monitoring / benchmarking) or just left as good practice guidelines.  @matuskalas will you please take a look at beta03 (once out) and close this issue if you agree we've gone as far as we can?

**Comment by joncison** [comment]
I propose to close this now, @matuskalas can always re-open if you think beta04 doesn't address all practical details.

**Comment by joncison** [comment]
@matuskalas ... please check that you're happy with the support for this in https://github.com/bio-tools/biotoolsSchema/tree/master/versions/biotools-2.0.0.  We can then proceed with the implementation (https://github.com/bio-tools/biotoolsregistry/issues/109) in due course and following the schedule defined in https://docs.google.com/document/d/1tqw7FELV4F_qzrTA9KpVYoORAeFPyY1ZOjaGTPN2H1E/edit

**Comment by joncison** [comment]
@matuskalas giving this a nudge to get your perspective on what we have in 2.0.0 is enough, or whether more can sensibly (== sustainably) be done.  Thanks !
