### ISSUE TITLE
Rename 'Component' to 'Plug-in' to minimise vagueness

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#53]
Wikipedia: "In computing, a plug-in (or plugin, add-in, addin, add-on, addon, or extension) is a software component that adds a specific feature to an existing computer program."

Synonyms: plugin, add-in, addin, add-on, addon, extension

NB.! JavaScript "components" are programmatic libraries, not plug-ins to an application.

**Comment by magnuspalmblad** [comment]
"Components" is also used to refer to parts or processing steps of workflows. So yes, the proposed name change is sound.

**Comment by matuskalas** [comment]
## AND NB.!

**Plug-in**s and **Library**-ies are types of **_Interfaces_**, while _e.g._  **Workflow**-s are types of **_Resource_**-s!

#### And we need an _is plug-in to_ relation!

**Examples**:

- ImageJ/Fiji macros: Resource **Workflow**, Interface **Plug-in**, _is plugin to_ ImageJ (| Fiji | ...)

- Galaxy workflows: Resource **Workflow**, Interface **Plug-in**, _is plugin to_ Galaxy (| Hyperbrowser | ...)

- CWL workflows: Resource **Workflow**, .... ?

**Comment by magnuspalmblad** [comment]
Was that a response to my comment (in 8 seconds)? If so, your typing speed is impressive! I was just agreeing the word "components" has many different meanings. Did not mean to add to any confusion!

**Comment by matuskalas** [comment]
@magnuspalmblad Nope, I wasn't that fast :-), but I fully agree with your comment :+1:  I was just adding thoughts about **_Resource_** versus **_Interface_** with respect to workflows/plug-ins/macros/script.

---

To continue my "... ?":
Do we need an _**Interface**_ type **Script**? For executable scripts (programs, workflows), that don't have **API**s (and thus aren't **Library**-ies). That would apply to CWL workflows, BASH scripts, Snakemake workflows, R and Python scripts that aren't packaged with an API as libraries, ....  Or do these then always have **_Interface_** type **Command line**? Opinions? @hmenager @jvanheld @mr-c @smoe ...

**Comment by mr-c** [comment]
Scripts, in the way I think about them, are executed from the command line (amongst other interfaces) -- so I don't understand what the `Interface` type `Script` would mean.

CWL descriptions of command line tools and the workflows built from them are executable from the command line as well (but are also executable from other context; like the Galaxy web-based GUI).

**Comment by joncison** [comment]
folks FYI in the bio.tools candidate stable schema (https://github.com/bio-tools/biotoolsxsd/tree/master/biotools-2.0-beta-01, see also See also https://docs.google.com/document/d/1tqw7FELV4F_qzrTA9KpVYoORAeFPyY1ZOjaGTPN2H1E/edit#heading=h.fffoc8urhpt8)  the notions of resource type and interface type have been merged, to yield e.g. "Command-line tool" and "Web application".   I think this is much clearer for users.

**Comment by matuskalas** [comment]
@joncison: I'm sceptical that merging **Interface**s and **Resource**s is a good idea. I'd rather see a tool | workflow | workbench | _etc._ **having interface** command-line | API | GUI | _etc._. Over-simplifying the reality may lead to even more and more chaotic and untrue tools annotations, doubtfully useful relations between tools, and in general limited value to bio.tools users.

---

@mr-c: There are some scripts that are executable in broadly used shells, _e.g._ BASH. And there are scripts in special languages, that need special interpreters to execute them, like CWL. How should those 2 groups be distinguished in bio.tools?  @hmenager @jvanheld @smoe

**Comment by mr-c** [comment]
@matuskalas Personally I don't distinguish between `bash`, `python`, or `cwl-runner` in a low level sense -- they are all text documents that begin with `#!` and the name of the interpreter ..

**Comment by matuskalas** [comment]
@mr-c Fair enough, perhaps that's a good practical simplification to label all those as having **CLI**s.

What then still stays for giving it some more thinking & discussing, is whether _**Resource**_ & **_Interface_** should be conflated or modelled. I still see too many reasons for the latter.

**Comment by joncison** [comment]
UPDATE

In 2.0-beta02 (out soon) 

* toolType of "Component" renamed to "Plugin"
* new toolType of "Script"
* you can pick 1 ... many toolType to describe an entry
* interfaceType is gone (but could be inferred from toolType(s) and labelled / searched upon in bio.tools UI) - cc @ekry 
* @mr-c  "Bash" is just a language (in <language> enum) and I added "CWL" there too. That should be enough for helping folk to find scripts tied to a particular language / run-time environment ?
* ps. "Library" is a toolType.  If you squint and read this as "Library is a bio.tools entry type" then this is OK

Hope this helps.
