### ISSUE TITLE
Add support for cell types, organelles, bio processes (GO), and for cell cultures, tissues, marker genes, molecule types (from somewhere), and maybe also biopolymer parts (SO)

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#54]
This is necessary for:

1. Enabling "end users" (_e.g._ biologists) to search using their terminology

2. Defining properly the scope of a tool|database|workflow

3. Not infecting, conflating, and exploding EDAM with these concepts

4. Making use of other people's work, where existent with good quality and maintenance (note1)

(note1) and where not, we should develop (or let someone develop) corresponding lightweight micro-ontologies

Support for such annotations can be implemented in steps, _i.e._ after already started with NCBI Taxonomy, continue with the next most obvious and stable (_i.e._ probably GO), _etc._

**Comment by joncison** [comment]
done in 2.0-beta-02

GO, SO and NCBI taxon ID  are all supported in biotoolsXSD (although support in bio.tools UI is not yet scheduled).  So I think we have all bases covered ?
