### ISSUE TITLE
Support for creator / editor of an entry i.e. acknowledge curation (was: Feature request from NEUBIAS taggathon)

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#55]
support <credit> for creator / editor of an entry i.e. acknowledge curation

**Comment by matuskalas** [comment]
This will be obvious when users are properly managed. But of course should be part of biotoolsSchema, with some user IDs (bio.tools user IDs and ORCIDs to start with, and more later)

When records are imported from another registry/catalogue, **the registrants/curators identity has to be recorded from user base there**. _I.e._ the users of an imported registry should be imported, in some way, too.

**Comment by joncison** [comment]
Done in 2.0-beta02

Extended <credit->role> enum to include "Documentor"

The rest can / will be captured within bio.tools i.e. "Last edited by" and maybe edit history.  cc @ekry FHI.  @matuskalas feel free create an issue on https://github.com/bio-tools/biotoolsregistry/issues/new (if one does not already exist) to track this.
