### ISSUE TITLE
Add license-like alternative of free use or payed

### ISSUE THREAD

**Issue by juanmirocks** [bio-tools/biotoolsSchema#56]
My concrete case: at tagtog.net we provide services for free for Academia & Research and private companies for low-demanding resources services. We offer extra services for private companies with a payment

Quick fix:

multiple-select of cost (free and commercial; or other)

**Comment by joncison** [comment]
OK, thanks - will consider this in the next release.

**Comment by joncison** [comment]
Done in 2.0-beta02 

< labels >< status > element can be specified multiple times.  Hope this is OK.  If we need to define a new  permissible value for this element, let us know.
