### ISSUE TITLE
toolType 1 or more

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsSchema#63]
The toolType (new in version 2) field does not specify if it allows 1 or more, just 1 , 0 or more etc. I would assume it is one or more, in any case it should probably be updated

**Comment by joncison** [comment]
How bizarre - it's appears constrained in XMLSpy.  Anyhow, I've fixed this (will update shortly)
`<xs:element name="toolType" minOccurs="1" maxOccurs="unbounded">`

**Comment by hansioan** [comment]
I'm just looking at the README.md file. I can update it there
