### ISSUE TITLE
resourceType and interfaceType in schema 2.0.0

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsSchema#64]
Are resourceType and interfaceType out of version 2?

The information requirements at:

http://biotoolsschemadocs.readthedocs.io/en/latest/information_requirement.html

and

https://github.com/bio-tools/biotoolsSchema#information-requirements

are not consistent.

**Comment by joncison** [comment]
Yes these elements are gone from 2.0.0

The tables are, I think, consistent, just need to scroll horizontally in the table on readthedocs to see the details.
