### ISSUE TITLE
software identifiers

### ISSUE THREAD

**Issue by mr-c** [bio-tools/biotoolsSchema#69]
Hello,

@matuskalas and I have been talking about the best way to represent identifiers for software such as DOIs, CPEs or [RRID](https://en.wikipedia.org/wiki/SciCrunch)s

[CPE identifiers](http://nvd.nist.gov/cpe.cfm) are used to [track security vulnerabilities](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures)

We think the DOI field should be replaced with a list of identifiers, each entry consisting of the name of the identifier and the identifier itself.
```
identifiers:
 - type: DOI
   value: 10.5281/zenodo.208182
 - type: RRID
   value: SCR_001156
 - type: CPE
   value: cpe:2.3:a:basespace_ruby_sdk_project:basespace_ruby_sdk:*:*:*:*:*:ruby:*:*
```
Thoughts?

**Comment by joncison** [comment]
+1 

Like this a lot, however, it would be a breaking change and I promised folks we'd restrict those to once / year (i.e. it could go in 3.*.*  /  Dec 2017 release)

**Comment by joncison** [comment]
Heads-up @mr-c, @matuskalas and @ekry 

I will (in biotools_dev.xsd)  create `summary->identifier` (0...many) with `identifier` having the (mandatory) elements of `value` (with appropriate regexes) and `type` (an enum).     I propose the following:

1. Refactor existing `summary->doi` element (breaking change)
2. Refactor existing `summary->toolID` (the bio.tools toolID) (breaking change) : @ekry @hans are there any implications here (beyond it being a breaking change generally) ?
3. Add RRID and CPE as suggested : can someone please tell me appropriate XSD-compatible regexes ??
4. Any other identifiers I should add ?

A valid value will have to be specified (otherwise bio.tools will choke) - so help on the regexes for any identifiers would be much appreciated.

**Comment by joncison** [comment]
PS.  currently there must be 1 only of `toolID` but in the new proposed model, `summary->identifier` would be optional, i.e. 0...many.  So I need a steer here @ekry and @hansioan and how / whether bio.tools would cope with that.

**Comment by joncison** [comment]
PPS: as for regexes I have:
* `RRID:.+`  (it needs the prefix, right?  as SciCrunch aren't the only provider, at least in principle)
* `cpe:.+` 
_i.e._ basically the prefix: than any old crap : can I be more restrictive ?

**Comment by joncison** [comment]
So the proposed model is:
![capture](https://user-images.githubusercontent.com/1506863/32327839-d5a50188-bfcf-11e7-8b04-a512f314fad3.PNG)

you'll notice I've moved `version` there, _i.e._ the version label can now be associated with a specific identifier.  I think this could be useful for various integration scenarios.

**Comment by mr-c** [comment]
(Tagging in @stain to correct anything I get wrong)

In CWL we model software identifiers as URIs (really, a list of strings) which has the following advantages:
 - We don't have to update our model to add another provider or registry
 - Anyone can determine that we are referring to a particular identifier by pattern matching on the full URI without having to know anything about our file format

**Comment by joncison** [comment]
Thanks Michael, that sounds sensible, and is pretty much what we have above, except value is just an xs:token, and can be explicitly typed; I just ponder whether it is / will always be the case that tool identifiers can be disambiguated via regex??  Anyhow, I could make `type` optional above (making it a bit easier to use).  cc @ekry @hansioan : what do you think?

**Comment by joncison** [comment]
`type` now optional, thus:
![capture](https://user-images.githubusercontent.com/1506863/32405110-a691498c-c156-11e7-90b8-52722631239d.PNG)

**Comment by matuskalas** [comment]
Reopening, as this needs at least a little bit of fixing.

A couple of thoughts:

* One nice example of these various IDs working together can be seen in Debian Med (thx @tillea and @smoe), _e.g._ https://blends.debian.org/med/tasks/bio (see the colourful links in the bottom left corner of a tool record).

* @mr-c @stain Could you please share 1 or more representative examples of tools IDs in CWL?

* All these ID types should be included into EDAM under _**Identifier**_, with regeces, and a new "URI scheme" attribute. Todo: open an issue there.

* _bio.tools_ ID can be modelled in _biotoolsSchema_ as either URI or a plain ID value. Both make sense and no strong opinions about either option. It should be defined as an `xs:simpleType` with Linked-Data- and therefore `xs:NCName`-compatible regex (see https://github.com/bio-tools/biotoolsSchema/issues/79#issuecomment-306793420 and https://github.com/bio-tools/biotoolsSchema/issues/79#issuecomment-343327595). **This needs fixing, ideally now, and also in the _bio.tools_ data.**

* For consideration is whether _**biotools**Schema_ should model _**biotools**IDs_ separately from "external" IDs, or not. Both options have pros and cons.

* Other, "external" IDs: included either **open** (either as **URIs** (https://github.com/bio-tools/biotoolsSchema/issues/69#issuecomment-341642445), or **idType+idValue** (works for URI-less IDs such as RRID), or best an `xs:choice` of the two), or defined as separate `xs:simpleType`s with regeces and `xs:appinfo`s (`appinfo`s incl. URI schemes, definitions, ...) - but even then keeping open for other IDs would be good.

* DOIs correspond to releases, not tools as a whole|brand. _N.B._ that they are never (not typically) assigned by SW developers or service providers (https://github.com/bio-tools/biotoolsSchema/blob/68248eb7a55b41e246f6710d05bd77bccc8b5753/biotools_dev.xsd line 179). **Can be fixed now.**

**Comment by joncison** [comment]
- For modelling of bio.tools ID (and other ID types) see recent changes and comments in https://github.com/bio-tools/biotoolsSchema/issues/79#issuecomment-306793420.  I've gone down the route of insisting on CURIEs for all identifiers _i.e._ syntax of "prefix:value" (e.g. "biotools:signal") which then are (or at least should be) trivially map-able to both something resolvable (_e.g._ https://bio.tools/signalp) or to the vanilla and xs:NCName-compatible identifier _(e.g._ "signalp").

- For now bio.tools IDs are lumped with the others.  Indeed pros and cons, I'm not too fussed.

- Comment on `identifier` changed to "A unique identifier of the software, typically assigned by an ID-assignment authority."

- Generally, IDs may or may not be version-specific; it's possible to specify version in model above (but see #76)

So, I close this again, for now, until we get any specific additional changes for biotoolsSchema.

**Comment by mr-c** [comment]
To answer @matuskalas's questions:

CWL example of a software identifier: 

```
hints:
  SoftwareRequirement:
    packages:
      interproscan:
        specs: [ "https://identifiers.org/rrid/RRID:SCR_005829" ]
        version: [ "5.21-60" ]
```
https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/InterProScan5.21-60.cwl#L25

Software RRIDs are not assigned to specific releases, but to the idea of a particular piece of software

**Comment by joncison** [comment]
**UPDATE**
biotoolsID and version information (for the bio.tools entry itself) are in their own elements - various discussion concluded this would lead to less confusion / problems.  Thus:
![capture](https://user-images.githubusercontent.com/1506863/32725003-53b81508-c86b-11e7-8568-061e4c6faf8f.PNG)

**Comment by matuskalas** [comment]
Element `type` is redundant, as these are in CURIE form.
https://github.com/bio-tools/biotoolsSchema/blob/753c572781d8d23a37eba2eb1d37a7728ec83b99/biotools_dev.xsd#L209
I suggest its removal, unless there is a use case of keeping it.

I'd say either `value`+`type` or `curie`. If resovable HTTP(S) URI have been ruled out, that is.

**Comment by joncison** [comment]
@hans, @ekry & I discussed this yesterday.  We could only safely remove it we assume all future otherIDs are indeed CURIEable.   We weren't 100% sure so we left it in (and also because it's useful to have an explicit enum of the types).    I think we could support HTTP(s) URIs in the existing model, if needed, because they have a prefix with a colon, _i.e._ "https:" or "http:".

So I think we leave it as-is for now.  If specified in a payload to PUT or POST the `otherID->type` value will simply be ignored.

**Comment by matuskalas** [comment]
Ok, @joncison. By leaving the `type` in, we allow for further backwards-compatible additions of un-CURIE-able and un-URI-able IDs :-)

However, as a note, allowing any other types of IDs and|or HTTP(s) URIs will also need a (backwards-compatible) change of the current schema, as it only allows the 3 patterns (doi, rrid, cpe).
