### ISSUE TITLE
Version the standard in a semver.org manner

### ISSUE THREAD

**Issue by mr-c** [bio-tools/biotoolsSchema#7]
```
Summary

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

http://semver.org/spec/v2.0.0.html

Thanks!

**Comment by joncison** [comment]
Yes, good suggestion.  This could work for biotoolsXSD.  Let's do this starting from next year - when the big release will thus be biotoolsXSD 2.0.0.   The plan is to make breaking changes but once a year, and backward compatible changes more regularly.

**Comment by joncison** [comment]
Hi Michael

If the gods smile on us, I should release biotoolsSchema 2.0.0 today :)
