### ISSUE TITLE
Unneccessary facets restrictions

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsSchema#71]
"biotoolsIdType" is restricted to be 1-12 length.

Primitive types that derive from it ("toolID", "versionID") also put the restriction 1-12.
In this case there is no no need to create a new anonymous type, so instead of 

```
<xs:simpleType>
  <xs:restriction base="biotoolsIdType">
    <xs:maxLength value="12"/>
    <xs:minLength value="1"/>
  </xs:restriction>
</xs:simpleType>
```
it is much clean just to put the type:

`<xs:element name="toolID" type="biotoolsIdType">`

**Comment by joncison** [comment]
Thanks!

`toolID` has been refactored (see https://github.com/bio-tools/biotoolsSchema/issues/69).  Only `relation->biotoolsId` is of this type, and doesn't have the problem above.
