### ISSUE TITLE
add tool authority attribute

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsSchema#74]
It would be great to have the authority field so we can have better compound tool id: 
"authority:id:version".  The example value for the authority would be an institution domain name.

**Comment by joncison** [comment]
I'm not sure this is needed : we stopped asking for a named "affiliation" when we updated the API last year, the institution domain would be the closest (that from credit->url field) but there can be more than one of these.

**Comment by redmitry** [comment]
I agree that the best way to define the authority would be the institution domain.
I recall back the BioMoby and LSIDs where authority IS the domain and form a part of the IDs...
The presence of domain is the metrics itself in the SSI - it is a part of the project identity.
For the ELIXIR Quality Metrics:
http://elixir.bsc.es/elixibilitas/
I am trying to get maximum from the biotoolsSchema 2.0, but many items doesn't exist yet.
You can find what metrics are already included in the model at the page.

**Comment by joncison** [comment]
I'd suggest you advertise the ELIXIR Quality Metrics website via registry-core ... telling folks what's next and getting some feedback

**Comment by joncison** [comment]
I think the _de facto_ authority is one of 
* `credit->url` (at least the domain part) where `credit->typeEntity`=="Institute" and `credit->typeRole` == "Provider"   (_i.e._ tractable, although a pain)
* `credit->orcidId` where `credit->typeEntity`=="Institute" and `credit->typeRole` == "Provider".  This would be awesome  **but** of course organisational ORCIDs are a work in progress (see https://github.com/bio-tools/biotoolsSchema/issues/87 and https://orcid.org/content/organization-identifier-working-group)

So I close this for now - can always reopen if necessary.
