### ISSUE TITLE
Consider associating version with publication

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#76]
as per bio.tools plan

**Comment by joncison** [comment]
@ekry @hansioan - I'm loath to do this until we have a clearer picture on how best to handle version-specific annotations.  I propose we park the issues for now - agree ?

**Comment by matuskalas** [comment]
I agree that we should develop the best way of handling **version-specific** and **version-unspecific** annotations, and everything inbetween.

However, _A non-existent perfect solution should not stand in the way of an imperfect solution._ In other words _We shouldn't let the **perfect** be the enemy of the **good**._ Instead, in cases like information management - what is what _bio.tools_ is all about - incremental development may lead to a good solution first, and a perfect solution later.

I think a first great version-related annotation to start with would be a simple `xs:simpleType`, _i.e._ a text string, allowing version annotations such as:
* simple example: "1.0"
* medium example: "2.0 - 2.7" (range)
* medium example: "1.1, 1.2.1, 1.4, v5" (list)
* complicated example: "1.1 - 1.4, 2.0-alpha, 2.0-beta-01 - 2.0-beta-04, 2.0.0" (list with ranges)
In the last case not the most beautifully presented information (sure), but extremely valuable information recorded (!!), still human readable when needed (!), and extremely simple to implement (!!!).
In addition, the simple example is expected in the majority cases, and the complicated example extremely rarely!

This kind of annotation could be attached as an **optional** (**always** optional!) `xs:element` or even `xs:attribute`(!) named _e.g._ `toolVersion` or rather `toolVersionList`. It could be first attached to one or more places in the _biotoolsSchema_. I suggest the following order of priority for attaching the version attribute (first 3-6 to start with?). Others please comment (incl. @hmenager @mr-c @albangaignard @smoe @tillea @dbolser @bgruening) Thanks!
- [ ] The _bio.tools_ tool record itself
- [ ] A download link
- [ ] A link to a package (_e.g. deb_), container, _etc._ 
- [ ] A publication
- [ ] A relation with another _bio.tools_ record. Here it needs both `toolVersion(List)` and `targetToolVersion(List)`
- [ ] A licence
- [ ] _etc._

_N.B._ that bigger changes between versions that would affect the high-level functionality or the whole scope or method of the tool (_i.e._ demanding _e.g._ different EDAM annotations and|or different description), should be recorded as **two separate _bio.tools_ entries**. That, however, also implies that their _bio.tools_ IDs must be different! Examples:
* ClustalW and ClustalOmega
* http://bio.tools/bowtie and http://bio.tools/bowtie2

**Comment by joncison** [comment]
I like the pragmatism here.  I ticked off (above) what's now done in biotoolsschema_dev.xsd.  NB. For the bio.tools record itself, this currently captured by 'summary->identifier->version'.

It's not done for `relation` (OTT, at least for now).  Or license (again, OTT for now).

My next commit will close this (can always be reopended if others have specific requests)
