### ISSUE TITLE
Local path in schema html file

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsSchema#78]
The html generated at:
https://github.com/bio-tools/biotoolsSchema/blob/master/versions/biotools-2.0.0/docs/biotools-2.0.0.html
contains as `schema location` a local file on a Windows installation at the location:
`D:\repos\GitHub\biotoolsSchema\versions\biotools-2.0.0\biotools-2.0.0.xsd`

Perhaps this location can be changed to the online `.xsd` file:
https://raw.githubusercontent.com/bio-tools/biotoolsSchema/master/versions/biotools-2.0.0/biotools-2.0.0.xsd

**Comment by joncison** [comment]
this was fixed in 3.0.0, see http://bio-tools.github.io/biotoolsSchema/
but I'll keep open for now to be sure not to repeat the mistake for 3.1.0
