### ISSUE TITLE
Natural language info for 'text mining' tools

### ISSUE THREAD

**Issue by martavillegas** [bio-tools/biotoolsSchema#81]
From text mining perspective, language is crucial but it refers to the language of input texts (users need to know if a given tool is for English or French texts).

**Comment by joncison** [comment]
Marking this as "won't fix" because I think it's a detail that is too fine-grained to be captured in the model or consider by bio.tools in a formal way (one could add a comment to the `function->comment` element though).   cc @matuskalas for his perspective.
