### ISSUE TITLE
How to handle attributes that are "not available" ?

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#82]
i.e. to support mooted information standard for bio.tools, based on biotoolsSchema.

The proposal is
* for attributes with enums, add "Not available" to the enum
* for publications, input, output, links and downloads, add a boolean to the corresponding types (``<publication>``, ``<input>``, ``<output>``, ``<link>`` and ``download``) e.g. "NotAvailable" which can be set true

I *think* this is better than a purely generic approach, e.g. simply adding a boolean for all attributes (which I think would bloat the schema / serialisation formats unnecessarily)

Thoughts?  cc @ekry

**Comment by hansioan** [comment]
I think at least one of "Not available" or "Not applicable" should apply to all the attributes marked with * (star). In this way we know they have been inspected and marked correspondingly , either with an annotation or with "Not available" / "Not applicable".

**Comment by joncison** [comment]
Absolutely

**Comment by joncison** [comment]
this done gracefully in biotools_dev.xsd for `doi`, `pmid` and `pmcid` elements under `publication`.

**Comment by joncison** [comment]
For `license' I added "Unlicensed" to the enum.

**Comment by joncison** [comment]
`urlftpType` simple type (as used by `link->url`, `download-url` and `documentation->url`) regex extended with "Not available" (as required by the bio.tools information standard (https://github.com/bio-tools/biotoolsSchemaDocs/blob/master/information_requirement.rst).

With the other changes (above) this nails, from the schema perspective, the issue of "Not available" in the information standard (https://github.com/bio-tools/biotoolsSchema/issues/77, https://github.com/bio-tools/biotoolsSchemaDocs/blob/master/information_requirement.rst)

**Comment by joncison** [comment]
footnote cc @hansioan  we'll soon have an "applicability matrix" of attributes in the standard (more precisely, biotoolsSchema elements) vs. tool types, which can be used when computing stats on compliance to the standards
