### ISSUE TITLE
Reduce maxlen of description

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#84]
1000 is too big, currently we're checking all entries with descriptions over 500 chars. 

A 250 char max. limit would be nice, but maybe impractical.

Eventually we can plan this based on what we have in the database.

cc @ekry and @hansioan FTI

**Comment by joncison** [comment]
@hansioan : I've been brutal, and dropped this to 500; is this OK?  The implication is that descriptions will have to be adjusted to fit in this new limit (https://github.com/bio-tools/biotoolsregistry/issues/278)

**Comment by hansioan** [comment]
@joncison that is fine, when the students curated the descriptions we decided to keep descriptions to max 500 chars
