### ISSUE TITLE
Failed to request ownership rights for this tool. Check your internet connection and try again

### ISSUE THREAD

**Issue by lassefolkersen** [bio-tools/biotoolsSchema#86]
I get an error when I try to request ownership of existing package:
Failed to request ownership rights for this tool. Check your internet connection and try again

It's odd because I have ok internet connection otherwise, it's eduroam, fairly strong signal, ok for other websites. I also tried an alternative (mobile hotspot), same result. I have attached a few screenshots, maybe could help find the issue?:
![01](https://user-images.githubusercontent.com/1732847/29716730-c700fa50-89ac-11e7-8a29-1478d3a2407c.PNG)

![02](https://user-images.githubusercontent.com/1732847/29716734-ca11ec7c-89ac-11e7-849a-4adec1f94cb1.PNG)

Other details: user lassefolkersen, package GeneRegionScan, browser version: chrome version 60.0.3112.101, windows 7 enterprise.

**Comment by ekry** [comment]
Thanks for the error report!

This is fixed now.

**Comment by lassefolkersen** [comment]
Thanks! Quick work
