### ISSUE TITLE
Standards for affiliation names

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#87]
Radka says ...

"Is there some affiliation standard or affiliation best practices in ELIXIR Service Registry?
Now, it looks little bit unstructured: EBI, Instruct, ELIXIR-Cz, Loschmidt Laboratories, ELIXIR-ITA-PADOVA, ..."

In the planned revisions, such standards will be applied to "service provider" names

Jon says ...
These are hard to enforce, but we could do something for ELIXIR nodes certainly, a maybe also for institutes if we can get a canonical list of institutes names / acronyms (see e.g. https://support.orcid.org/knowledgebase/articles/276884-how-are-organizations-identified-in-orcid and http://www.oclc.org/research/publications/2016/oclcresearch-organizational-identifiers-and-isni-2016.html (ISNI Organizational Identifiers)

**Comment by matuskalas** [comment]
After many failed attempts, there is a promising global standard under development: https://orcid.org/content/organization-identifier-working-group I assume they'll come up with a solution rather soon, meybe next year.

**Comment by joncison** [comment]
Fantastic if we get organisation ORCIDs

**Comment by joncison** [comment]
folks, I'm setting this as "wrong tracker" because it's already supported in in biotoolsSchema (at least, by use of ORCIDs for organisations when they come) and in bio.tools it should be fixed by use of a controlled vocabulary for institutions (in the meantime), see https://github.com/bio-tools/biotoolsRegistry/issues/334.
