### ISSUE TITLE
Resource types: Docker images vs VMs

### ISSUE THREAD

**Issue by abdulrahmanazab** [bio-tools/biotoolsSchema#9]
In the 'resource types' list, there is a type 'container' under which both docker images and VMs are categorized.
This is conceptually 'wrong'. Linux containerization is a totally different concept from VM. While each VM has its own OS, containers use the underlying kernel of the host OS. For containers, the underlying kernel must be Linux.

Also categorizing VMs under 'container' is confusing and misleading.

Also in dockers, the resource is called 'image' not 'container'. It is a container when it runs, but the resource is an image.

What I suggest is having two categories instead of one:
- Virtual machine
- Docker image

**Comment by joncison** [comment]
The release is now out and I *think* it addresses what you suggest, but please take a look and reopen if necessary.
