### ISSUE TITLE
Consistent use of xs:token

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsSchema#90]
This should be the default for most simple text attributes

See https://www.w3schools.com/xml/schema_dtypes_string.asp

Check exhaustively: certainly ``nameType`` (as used e.g. by "name" attribute) which is a restriction of ``xs:string`` currently should be a restriction of xs:token.

**Comment by matuskalas** [comment]
The problem is that the behaviour of xs:token is implementation-dependent.

An alternative used in BioXSD is bx:Name:

```
<xs:simpleType name="Name">
    <!--= NB. Different from xs:Name which is a valid name of an XML tag. =-->
    <xs:restriction base="xs:string">
        <xs:pattern value="\S(\S|\s\S)*"/>
        <xs:maxLength value="1000"/>
    </xs:restriction>
</xs:simpleType>
```

This ensures that all the undesired white spaces are forbidden in all contexts.

**Comment by joncison** [comment]
Things that were (but shouldn't have been) using `xs:string` are now using `xs:token` (the default type basically).   As for the implementation-dependent behaviour, I'll worry about this if we hit a problem.
