### ISSUE TITLE
Enable a Zenodo DOI before the 3.0.0 release

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#95]
This is best done by someone with rights to the https://github.com/bio-tools organisation, by logging in with his GitHub credentials to Zenodo, clicking the "GitHub" button, and "turning on" the bio-tools/biotoolsSchema repo.

The Zenodo's access to the https://github.com/bio-tools organisation will have to be confirmed in GitHub.

(I could also do all this, but then I need adequate rights to the https://github.com/bio-tools organisation)

**Comment by joncison** [comment]
done!

what I'd appreciate is your help to ensure we do a professional job of releasing biotoolsSchema 3.0.0, when the time comes.

**Comment by matuskalas** [comment]
Cool!

Ok, then assign #96.
