### ISSUE TITLE
Make a proper release when ready

### ISSUE THREAD

**Issue by matuskalas** [bio-tools/biotoolsSchema#96]
This includes first:

- [x] Enabling DOIs (#95).

- [ ] Formatting CHANGELOG.md.

- [ ] Creating a _releases_stable_ folder with a _biotools.xsd_ containing all stable releases (not _alpha_ and _beta_) as successive commits.

- [ ] Ditto with _releases_all_ (incl. _alpha_ and _beta_ releases).

- [ ] Add the final file(s) into a new dedicated folder in the _versions_ folder. And add the final _.xsd_ as a new commit of _biotools.xsd_ in _releases_all_ (and in _releases_stable_ if applicable). Commit.

And then:

- [ ] Create a release proper, incl. release notes and uploaded "binaries".

Assign either to @joncison, @hmenager, or @matuskalas.

**Comment by matuskalas** [comment]
Assigning myself (https://github.com/bio-tools/biotoolsSchema/issues/95#issuecomment-344558009), but I won't be able to do it within this week.

**Comment by joncison** [comment]
This is really helpful, thanks.  It'll be next week before we have the file ready, anyway.

**Comment by joncison** [comment]
heads-up @matuskalas  I plan to release a 3.0.0rc ideally today, allowing then 1 week for inspection by some of the core guys around biotoolsSchema, aiming for the full release of 3.0.0 by the end of next week

**Comment by joncison** [comment]
3.0.0-rc now out : https://github.com/bio-tools/biotoolsSchema/tree/master/versions/biotools-3.0.0-rc

cc @matuskalas

**Comment by joncison** [comment]
Think we can close this ... we have a reasonably well formatted [changelog](https://github.com/bio-tools/biotoolsSchema/blob/master/CHANGELOG.md), and directories for [versions ](https://github.com/bio-tools/biotoolsSchema/tree/master/versions) and the latest [stable ](https://github.com/bio-tools/biotoolsSchema/tree/master/stable) release.  [SemVer ](https://semver.org/)version label rules are used.
